/**
 * Auto-generated thin instance for `sap-ai-core`.
 * Wire format: OpenAI-compatible Chat Completions.
 *
 * DO NOT hand-edit — this file is regenerated by
 * `scripts/build-registry.ts`. To customise behaviour, edit the
 * shared OpenAI-compatible transport in `src/providers/openai-compatible/`
 * or add a custom adapter folder and reference it from the build script.
 */
import { OpenAICompatibleTransport } from '../openai-compatible/index.js';
import { makeError } from '../../errors.js';
import type { OpenAICompatibleConfig } from '../openai-compatible/index.js';
import type { TransportMetadata } from '../../types.js';

export interface ProviderConfig extends OpenAICompatibleConfig {}

export class SapAiCoreTransport extends OpenAICompatibleTransport {
  constructor(config: ProviderConfig) {
    if (!config.baseURL) {
      throw makeError({
        code: 'INVALID_CONFIGURATION',
        transport: 'sap-ai-core',
        message: 'Transport "sap-ai-core" requires a baseURL',
      });
    }
    super(config);
  }

  override capabilities(): TransportMetadata {
    const m = super.capabilities();
    return { ...m, name: 'sap-ai-core', defaultBaseURL: 'https://api.ai.<region>.<landscape>.ml.hana.ondemand.com/v2' };
  }
}

/** Canonical default base URL for this provider. */
export const DEFAULT_BASE_URL = 'https://api.ai.<region>.<landscape>.ml.hana.ondemand.com/v2';
